version: '3.8'
services:
  article-extractor:  # renamed service for clarity
    image: node:20
    working_dir: /app
    volumes:
      - ./:/app
    command: npm start
    ports:
      - "3000:3000"
    depends_on:
      - mongo
  mongo:
    image: mongo:latest
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data: